# 2.1 Data manipulation

## 2.1.1. Getting Started

In [44]:
import torch
import numpy

torch.manual_seed(42)

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [6]:
x = torch.arange(12, dtype=torch.float32)
print(x)

# number of elements
print(x.numel())

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
12


In [8]:
# shape
x.shape

torch.Size([12])

In [12]:
# reshape
X = x.reshape(3,4)
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [13]:
X = x.reshape(4,3)
print(X)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [15]:
# zeros: torch.zeros([shape])
X = torch.zeros((2, 2, 3, 4))
X

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [17]:
X = torch.ones((2,3,4))
X

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
# random - Gaussian distribution
X = torch.randn(3, 4)
X

tensor([[-0.1768, -0.3235,  1.0862, -0.5769],
        [-0.0477, -0.3609,  0.4087,  0.8236],
        [ 1.0553,  0.1042, -0.4949, -1.1694]])

In [27]:
# self-defition
X = torch.tensor([[1,2,3], [4, 5, 6], [7, 8, 9]])
X

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 2.1.2. Indexing and Slicing

It is applied along axis 0

[-1] selects the last row and [1:3] selects the second and third rows.

In [28]:
# X[start:stop]
X[-1]

tensor([7, 8, 9])

In [29]:
X[0:2]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
X[-3:-1]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
# element: X[1][2] ~ X[1, 2]
X[1,2], X[1][2]

(tensor(6), tensor(6))

In [40]:
X[:2, :] = 12
X

tensor([[12, 12, 12],
        [12, 12, 12],
        [ 7,  8,  9]])

In [52]:
torch.manual_seed(42)
A = torch.randn((2, 3, 4, 4), dtype=torch.float32)
A

tensor([[[[ 1.9269,  1.4873,  0.9007, -2.1055],
          [ 0.6784, -1.2345, -0.0431, -1.6047],
          [-0.7521,  1.6487, -0.3925, -1.4036],
          [-0.7279, -0.5594, -0.7688,  0.7624]],

         [[ 1.6423, -0.1596, -0.4974,  0.4396],
          [-0.7581,  1.0783,  0.8008,  1.6806],
          [ 1.2791,  1.2964,  0.6105,  1.3347],
          [-0.2316,  0.0418, -0.2516,  0.8599]],

         [[-1.3847, -0.8712, -0.2234,  1.7174],
          [ 0.3189, -0.4245,  0.3057, -0.7746],
          [-1.5576,  0.9956, -0.8798, -0.6011],
          [-1.2742,  2.1228, -1.2347, -0.4879]]],


        [[[-0.9138, -0.6581,  0.0780,  0.5258],
          [-0.4880,  1.1914, -0.8140, -0.7360],
          [-1.4032,  0.0360, -0.0635,  0.6756],
          [-0.0978,  1.8446, -1.1845,  1.3835]],

         [[ 1.4451,  0.8564,  2.2181,  0.5232],
          [ 0.3466, -0.1973, -1.0546,  1.2780],
          [-0.1722,  0.5238,  0.0566,  0.4263],
          [ 0.5750, -0.6417, -2.2064, -0.7508]],

         [[ 0.0109, -0.3387,

In [56]:
A[0:1, :]

tensor([[[[ 1.9269,  1.4873,  0.9007, -2.1055],
          [ 0.6784, -1.2345, -0.0431, -1.6047],
          [-0.7521,  1.6487, -0.3925, -1.4036],
          [-0.7279, -0.5594, -0.7688,  0.7624]],

         [[ 1.6423, -0.1596, -0.4974,  0.4396],
          [-0.7581,  1.0783,  0.8008,  1.6806],
          [ 1.2791,  1.2964,  0.6105,  1.3347],
          [-0.2316,  0.0418, -0.2516,  0.8599]],

         [[-1.3847, -0.8712, -0.2234,  1.7174],
          [ 0.3189, -0.4245,  0.3057, -0.7746],
          [-1.5576,  0.9956, -0.8798, -0.6011],
          [-1.2742,  2.1228, -1.2347, -0.4879]]]])

## 2.1.3. Operations

- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication
- Sum
- Mean
- Max / Min
- Concatenation
- Broadcasting

In [57]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [ ]:
x = torch.tensor([1., 2., 4., 8.])
y = torch.tensor([2., 2., 2., 2.])
# x + y, x - y, x * y, x / y, x ** y
print(x)
print(y)

tensor([1., 2., 4., 8.])
tensor([2, 2, 2, 2])


In [75]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [76]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [77]:
x * y

tensor([ 2.,  4.,  8., 16.])

In [78]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [79]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [ ]:
# torch.arange([num_of_element], dtype=[data_type]) 
X = torch.arange(12, dtype=torch.float32).reshape((3,4)) # arange reshape (n, m) => n * m = number of elements
print(X)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(Y)

# concat
Z = torch.cat((X, Y), dim=0)
print(Z)
W = torch.cat((X, Y), dim=1)
print(W)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [71]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

## 2.1.4. Broadcasting

Broadcasting rule: PyTorch compares tensor shapes from right to left. Two dimensions are compatible if
1. They are equal
2. One of them is 1
3. One dimension is missing

Broadcasting works according to the following two-step procedure: 
1. expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape; 

2. perform an elementwise operation on the resulting arrays.

In [84]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(6).reshape((3, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1],
         [2, 3],
         [4, 5]]))

In [85]:
a + b

tensor([[0, 1],
        [3, 4],
        [6, 7]])

In [81]:
a - b

tensor([[ 0, -1],
        [ 1,  0],
        [ 2,  1]])

In [86]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

b = torch.tensor([10, 20, 30])

C = A + b
print(C)

tensor([[11, 22, 33],
        [14, 25, 36]])


## 2.1.5. Saving Memory

Note that after we run Y = Y + X, id(Y) points to a different location. That is because Python first evaluates Y + X, allocating new memory for the result and then points Y to this new location in memory.

In [87]:
before = id(Y)
Y = Y + X
id(Y) == before

False

We can assign the result of an operation to a previously allocated array Y by using slice notation: Y[:] = <expression>. 

To illustrate this concept, we overwrite the values of tensor Z, after initializing it, using zeros_like, to have the same shape as Y.

In [89]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1935761351888
id(Z): 1935761351888


In [90]:
before = id(X)
X += Y
id(X) == before

True